My Project: CalculationMatrix Class Reference
CalculationMatrix Class Reference
A matrix used primarily for diagonalized calculations.
#include <Matrix.h>
Public Member Functions
CalculationMatrix (int x_size, int y_size=1, int z_size=1, int n_of_diags=1)
void Initialize (int x_size, int y_size=1, int z_size=1, int n_of_diags=1)
int index1d (int x, int y=0, int z=0)
void writeToFile (string filename)
Matrix1D< double > operator* (Matrix1D< double > &V) const
FUNCTION NOT IMPLEMENTED.
Public Attributes
bool initialized
Variables used for denoting whether it is initialized or not.
int x_size
size in x direction of matrix
int y_size
size in y direction of matrix
int total_size
total size of matrix
string change_ind
Variables useful for changes tracking (store here time when changed)
Detailed Description
A matrix used primarily for diagonalized calculations.
Model matrix (or related matrices) It is based on DiagMatrix and have methods for conversion from 3D or 2D PSD (and related) arrays into 1d array of unknown elements
Constructor & Destructor Documentation
CalculationMatrix::CalculationMatrix (int x_size, int y_size = 1, int z_size = 1, int n_of_diags = 1)
Constructor for CalculationMatrix class.
Parameters
x_size - x size
y_size - y size
z_size - z size
n_of_diags - NUMBER OF DIAGONALS ABOVE THE MAIN DIAGONAL (main diagonal is not counted)
Member Function Documentation
int CalculationMatrix::index1d (int x, int y = 0, int z = 0)
Function returns 1d index for 2D-3D arrays
Referenced by AddBoundaries_1D(), AddBoundaries_2D(), AnySecondDerivativeApproximation_2D(), AnySecondDerivativeApproximation_2D_y(), Diffusion_1D(), MakeModelMatrix_2D_ADI1_x(), MakeModelMatrix_2D_ADI1_y(), MakeModelMatrix_2D_ADI2_x(), MakeModelMatrix_2D_ADI2_y(), MakeModelMatrix_2D_ADI3_x(), MakeModelMatrix_2D_ADI3_y(), SecondDerivativeApproximation_1D(), SecondDerivativeApproximation_2D(), and SecondDerivativeApproximation_2D_y().
void CalculationMatrix::Initialize (int x_size, int y_size = 1, int z_size = 1, int n_of_diags = 1)
Allocating memory for CalculationMatrix, Setting the diagonals to be 0
void CalculationMatrix::writeToFile (string filename)
Save matrix to file. Includes varaible names and sizes
The documentation for this class was generated from the following files:
Matrix.h
Matrix.cpp