My Project: Opm::MonotCubicInterpolator Class Reference
Opm::MonotCubicInterpolator Class Reference
Represents one dimensional function f with single valued argument x that can be interpolated using monotone cubic interpolation.
#include <MonotCubicInterpolator.hpp>
Public Member Functions
MonotCubicInterpolator (const std::string &datafilename) throw (const char*)
MonotCubicInterpolator (const char *datafilename) throw (const char*)
MonotCubicInterpolator (const char *datafilename, int xColumn, int fColumn) throw (const char*)
MonotCubicInterpolator (const std::string &datafilename, int xColumn, int fColumn) throw (const char*)
MonotCubicInterpolator (const std::vector< double > &x, const std::vector< double > &f)
MonotCubicInterpolator ()
bool read (const std::string &datafilename)
bool read (const std::string &datafilename, int xColumn, int fColumn)
double operator() (double x) const
double evaluate (double x) const throw (const char*)
double evaluate (double x, double &errorestimate_output) const
std::pair< double, double > getMinimumX () const
std::pair< double, double > getMaximumX () const
std::pair< double, double > getMaximumF () const throw (const char*)
std::pair< double, double > getMinimumF () const throw (const char*)
std::vector< double > get_xVector () const
std::vector< double > get_fVector () const
void scaleData (double factor)
bool isStrictlyMonotone ()
bool isMonotone () const
bool isStrictlyIncreasing ()
bool isMonotoneIncreasing () const
bool isStrictlyDecreasing ()
bool isMonotoneDecreasing () const
void addPair (double newx, double newf) throw (const char*)
std::pair< double, double > getMissingX () const throw (const char*)
std::string toString () const
int getSize () const
void chopFlatEndpoints (const double)
void chopFlatEndpoints ()
void shrinkFlatAreas (const double)
void shrinkFlatAreas ()
Private Member Functions
double H00 (double t) const
Hermite Basis function - H00.
double H10 (double t) const
Hermite Basis function - H10.
double H01 (double t) const
Hermite Basis function - H01.
double H11 (double t) const
Hermite Basis function - H11.
void computeInternalFunctionData () const
void computeSimpleDerivatives () const
void adjustDerivativesForMonotoneness () const
bool isMonotoneCoeff (double alpha, double beta) const
Private Attributes
std::map< double, double > data
Data structure to store x- and f-values.
std::map< double, double > ddata
Data structure to store x- and d-values.
bool strictlyMonotoneCached
Flag to determine whether the boolean strictlyMonotone can be trusted.
bool monotoneCached
Flag to determine whether the boolean Monotone can be trusted.
bool strictlyMonotone
strictly monotone function
bool monotone
monotone function, not strictly monotone
bool strictlyDecreasing
if strictlyMonotone is true, tells whether function is strictly decreasing
bool strictlyIncreasing
if strictlyMonotone is true, tells whether function is strictly increasing
bool decreasing
tells whether function is decreasing
bool increasing
tells whether function is increasing
Detailed Description
Represents one dimensional function f with single valued argument x that can be interpolated using monotone cubic interpolation.
Constructor & Destructor Documentation
Opm::MonotCubicInterpolator::MonotCubicInterpolator (const std::string & datafilename) throw (const char *) inline
Parameters
datafilename A datafile with the x values and the corresponding f(x) values
Accepts a filename as input and parses this file for two-column floating point data, interpreting the data as representing function values x and f(x).
Ignores all lines not conforming to <whitespace><float><whitespace><float><whatever><newline>
References read().
Opm::MonotCubicInterpolator::MonotCubicInterpolator (const char * datafilename) throw (const char *) inline
Parameters
datafilename A datafile with the x values and the corresponding f(x) values
Accepts a filename as input and parses this file for two-column floating point data, interpreting the data as representing function values x and f(x).
Ignores all lines not conforming to <whitespace><float><whitespace><float><whatever><newline>
All commas in the file will be treated as spaces when parsing.
References read().
Opm::MonotCubicInterpolator::MonotCubicInterpolator (const char * datafilename, int xColumn, int fColumn) throw (const char *) inline
Parameters
datafilename data file
XColumn x values
fColumn f values
Accepts a filename as input, and parses the chosen columns in that file.
References read().
Opm::MonotCubicInterpolator::MonotCubicInterpolator (const std::string & datafilename, int xColumn, int fColumn) throw (const char *) inline
Parameters
datafilename data file
XColumn x values
fColumn f values
Accepts a filename as input, and parses the chosen columns in that file.
References read().
Opm::MonotCubicInterpolator::MonotCubicInterpolator (const std::vector< double > & x, const std::vector< double > & f)
Parameters
x vector of x values
f vector of corresponding f values
Accepts two equal-length vectors as input for constructing the interpolation object. First vector is the x-values, the second vector is the function values
Opm::MonotCubicInterpolator::MonotCubicInterpolator () inline
No input, an empty function object is created.
This object must be treated with care until populated.
Member Function Documentation
void Opm::MonotCubicInterpolator::addPair (double newx, double newf) throw (const char *)
Parameters
newx New x point
newf New f(x) point
Adds a new datapoint to the function.
This causes all the derivatives at all points of the functions to be recomputed and then adjusted for monotone cubic interpolation. If this function ever enters a critical part of any code, the locality of the algorithm for monotone adjustment must be exploited.
void Opm::MonotCubicInterpolator::adjustDerivativesForMonotoneness () const private
Adjusts the derivative values (ddata) so that we can guarantee that the resulting piecewise Hermite polymial is monotone. This is done according to the algorithm of Fritsch and Carlsson 1980, see Section 4, especially the two last lines.
void Opm::MonotCubicInterpolator::chopFlatEndpoints (const double epsilon)
Checks if the function curve is flat at the endpoints, chop off endpoint data points if that is the case.
The notion of "flat" is determined by the input parameter "epsilon" Values whose difference are less than epsilon are regarded as equal.
This is implemented to be able to obtain a strictly monotone curve from a data set that is strictly monotone except at the endpoints.
Example: The data points (1,3), (2,3), (3,4), (4,5), (5,5), (6,5) will become (2,3), (3,4), (4,5)
Assumes at least 3 datapoints. If less than three, this function is a loop.
void Opm::MonotCubicInterpolator::chopFlatEndpoints () inline
Wrapper function for chopFlatEndpoints(const double) providing a default epsilon parameter
void Opm::MonotCubicInterpolator::computeInternalFunctionData () const private
Sets the following information (booleans) about the function to true or false, default is true for all
strictlyMonotone, monotone, strictlyDecreasing, decreasing, strictlyIncreasing, increasing
Referenced by isMonotone(), isMonotoneDecreasing(), isMonotoneIncreasing(), isStrictlyDecreasing(), isStrictlyIncreasing(), and isStrictlyMonotone().
void Opm::MonotCubicInterpolator::computeSimpleDerivatives () const private
Computes initial derivative values using centered (second order) difference for internal datapoints, and one-sided derivative for endpoints
The internal datastructure map<double,double> ddata is populated by this method.
double Opm::MonotCubicInterpolator::evaluate (double x) const throw (const char *)
Parameters
x x value
Returns f(x) for given x (input). Interpolates (monotone cubic or linearly) if necessary.
Extrapolates using the constants f(x_min) or f(x_max) if input x is outside (x_min, x_max)
Returns
f(x) for a given x
Referenced by Cubic1D(), and operator()().
double Opm::MonotCubicInterpolator::evaluate (double x, double & errorestimate_output) const
Parameters
x x value
errorestimate_output Returns f(x) and an error estimate for given x (input).
Interpolates (linearly) if necessary.
Throws an exception if extrapolation would be necessary for evaluation. We do not want to do extrapolation (yet).
The error estimate for x1 < x < x2 is (x2 - x1)^2/8 * f''(x) where f''(x) is evaluated using the stencil (1 -2 1) using either (x0, x1, x2) or (x1, x2, x3);
Throws an exception if the table contains only two x-values.
NOT IMPLEMENTED YET!
vector< double > Opm::MonotCubicInterpolator::get_fVector () const
Provide a copy of tghe function data as a vector
Unspecified order, but corresponds to get_xVector
Returns
f values as a vector
vector< double > Opm::MonotCubicInterpolator::get_xVector () const
Provide a copy of the x-data as a vector
Unspecified order, but corresponds to get_fVector.
Returns
x values as a vector
pair< double, double > Opm::MonotCubicInterpolator::getMaximumF () const throw (const char *)
Maximum f-value, returns both x and f in a pair.
Returns
x value corresponding to maximum f value
maximum f value
std::pair<double,double> Opm::MonotCubicInterpolator::getMaximumX () const inline
Maximum x-value, returns both x and f in a pair.
Returns
maximum x value
f(maximum x value)
References data.
pair< double, double > Opm::MonotCubicInterpolator::getMinimumF () const throw (const char *)
Minimum f-value, returns both x and f in a pair
Returns
x value corresponding to minimal f value
minimum f value
std::pair<double,double> Opm::MonotCubicInterpolator::getMinimumX () const inline
Minimum x-value, returns both x and f in a pair.
Returns
minimum x value
f(minimum x value)
References data.
pair< double, double > Opm::MonotCubicInterpolator::getMissingX () const throw (const char *)
Returns an x-value that is believed to yield the best improvement in global accuracy for the interpolation if computed.
Searches for the largest jump in f-values, and returns a x value being the average of the two x-values representing the f-value-jump.
Returns
New x value beleived to yield the best improvement in global accuracy
Maximal difference
int Opm::MonotCubicInterpolator::getSize () const inline
Returns
Number of datapoint pairs in this object
References data.
bool Opm::MonotCubicInterpolator::isMonotone () const inline
Determines if the current function-value-data is monotone.
Returns
True if f(x) is monotone, else False
References computeInternalFunctionData(), monotone, and monotoneCached.
bool Opm::MonotCubicInterpolator::isMonotoneCoeff (double alpha, double beta) const inline private
Checks if the coefficient alpha and beta is in the region that guarantees monotoneness of the derivative values they represent
See Fritsch and Carlson 1980, Lemma 2, alternatively Step 5 in Wikipedia's article on Monotone cubic interpolation.
bool Opm::MonotCubicInterpolator::isMonotoneDecreasing () const inline
Determines if the current function-value-data is monotone and decreasing
Returns
True if f(x) is monotone and decreasing, else False
References computeInternalFunctionData(), decreasing, monotone, and monotoneCached.
bool Opm::MonotCubicInterpolator::isMonotoneIncreasing () const inline
Determines if the current function-value-data is monotone and increasing.
Returns
True if f(x) is monotone and increasing, else False
References computeInternalFunctionData(), increasing, monotone, and monotoneCached.
bool Opm::MonotCubicInterpolator::isStrictlyDecreasing () inline
Determines if the current function-value-data is strictly decreasing. This is a utility function for outsiders if they want to invert the data for example.
Returns
True if f(x) is strictly decreasing, else False
References computeInternalFunctionData(), strictlyDecreasing, strictlyMonotone, and strictlyMonotoneCached.
bool Opm::MonotCubicInterpolator::isStrictlyIncreasing () inline
Determines if the current function-value-data is strictly increasing. This is a utility function for outsiders if they want to invert the data for example.
Returns
True if f(x) is strictly increasing, else False
References computeInternalFunctionData(), strictlyIncreasing, strictlyMonotone, and strictlyMonotoneCached.
bool Opm::MonotCubicInterpolator::isStrictlyMonotone () inline
Determines if the current function-value-data is strictly monotone. This is a utility function for outsiders if they want to invert the data for example.
Returns
True if f(x) is strictly monotone, else False
References computeInternalFunctionData(), strictlyMonotone, and strictlyMonotoneCached.
double Opm::MonotCubicInterpolator::operator() (double x) const inline
Parameters
x x value
Returns f(x) for given x (input). Interpolates (monotone cubic or linearly) if necessary.
Extrapolates using the constants f(x_min) or f(x_max) if input x is outside (x_min, x_max)
Returns
f(x) for a given x
References evaluate().
bool Opm::MonotCubicInterpolator::read (const std::string & datafilename) inline
Parameters
datafilename A datafile with the x values and the corresponding f(x) values
Accepts a filename as input and parses this file for two-column floating point data, interpreting the data as representing function values x and f(x).
returns true on success
All commas in file will be treated as spaces when parsing
Ignores all lines not conforming to <whitespace><float><whitespace><float><whatever><newline>
Referenced by MonotCubicInterpolator().
bool Opm::MonotCubicInterpolator::read (const std::string & datafilename, int xColumn, int fColumn)
Parameters
datafilename data file
XColumn x values
fColumn f values
Accepts a filename as input, and parses the chosen columns in that file.
void Opm::MonotCubicInterpolator::scaleData (double factor)
Parameters
factor Scaling constant
Scale all the function value data by a constant
void Opm::MonotCubicInterpolator::shrinkFlatAreas (const double epsilon)
If function is monotone, but not strictly monotone, this function will remove datapoints from intervals with zero derivative so that the curve become strictly monotone.
Example The data points (1,2), (2,3), (3,4), (4,4), (5,5), (6,6) will become (1,2), (2,3), (3,4), (5,5), (6,6)
Assumes at least two datapoints, if one or zero datapoint, this is a noop.
void Opm::MonotCubicInterpolator::shrinkFlatAreas () inline
Wrapper function for shrinkFlatAreas(const double) providing a default epsilon parameter
string Opm::MonotCubicInterpolator::toString () const
Constructs a string containing the data in a table
Returns
a string containing the data in a table
The documentation for this class was generated from the following files:
MonotCubicInterpolator.hpp
MonotCubicInterpolator.cpp