var searchData=
[
  ['calculationmatrix',['CalculationMatrix',['../class_calculation_matrix.html',1,'CalculationMatrix'],['../class_calculation_matrix.html#a5c1345d1761377c1597c367b4e1fdfc9',1,'CalculationMatrix::CalculationMatrix()']]],
  ['change_5find',['change_ind',['../class_matrix3_d.html#a32921764532ebc755b4b2e569b9a680f',1,'Matrix3D::change_ind()'],['../class_matrix4_d.html#a1cbcd4f5e0fe533be3e696335a0d811d',1,'Matrix4D::change_ind()'],['../class_calculation_matrix.html#afec1f2436aef138ed79e25220cf89f93',1,'CalculationMatrix::change_ind()']]],
  ['chopflatendpoints',['chopFlatEndpoints',['../class_opm_1_1_monot_cubic_interpolator.html#a83a92d8a6e6bd6719ef9102af51ca74a',1,'Opm::MonotCubicInterpolator::chopFlatEndpoints(const double)'],['../class_opm_1_1_monot_cubic_interpolator.html#afd92b5866850437e66e01e092fc8f8b2',1,'Opm::MonotCubicInterpolator::chopFlatEndpoints()']]],
  ['close',['close',['../class_parameters.html#a62ef757722bbaecc24642b2c20d7d3bb',1,'Parameters']]],
  ['computeinternalfunctiondata',['computeInternalFunctionData',['../class_opm_1_1_monot_cubic_interpolator.html#a0fb655f39c0428a162e0bab3a9dfab03',1,'Opm::MonotCubicInterpolator']]],
  ['computesimplederivatives',['computeSimpleDerivatives',['../class_opm_1_1_monot_cubic_interpolator.html#a3d03d08341bfd5e7ebaee7c58fed9bfc',1,'Opm::MonotCubicInterpolator']]],
  ['convection_5f1d_5fultimate_5fquickest6',['Convection_1D_ULTIMATE_QUICKEST6',['../_convection__1_d___u_l_t_i_m_a_t_e___q_u_i_c_k_e_s_t6_8cpp.html#a99be0c4fdade458f03ad84348eae2ef7',1,'Convection_1D_ULTIMATE_QUICKEST6(Matrix1D&lt; double &gt; &amp;PSD, Matrix1D&lt; double &gt; x, int x_size, double x_LBC, double x_UBC, string x_LBC_type, string x_UBC_type, Matrix1D&lt; double &gt; Ux, Matrix1D&lt; double &gt; Sources, Matrix1D&lt; double &gt; Losses, double dt_total):&#160;Convection_1D_ULTIMATE_QUICKEST6.cpp'],['../_convection__1_d___u_l_t_i_m_a_t_e___q_u_i_c_k_e_s_t6_8h.html#af94a11ee22da26ed27cf9008db9b44e8',1,'Convection_1D_ULTIMATE_QUICKEST6(Matrix1D&lt; double &gt; &amp;PSD, Matrix1D&lt; double &gt; x, int x_size, double x_LBC, double x_UBC, string x_LBC_type, string x_UBC_type, Matrix1D&lt; double &gt; Ux, Matrix1D&lt; double &gt; Sources, Matrix1D&lt; double &gt; Losses, double dt):&#160;Convection_1D_ULTIMATE_QUICKEST6.cpp']]],
  ['convection_5f1d_5fultimate_5fquickest6_2ecpp',['Convection_1D_ULTIMATE_QUICKEST6.cpp',['../_convection__1_d___u_l_t_i_m_a_t_e___q_u_i_c_k_e_s_t6_8cpp.html',1,'']]],
  ['convection_5f1d_5fultimate_5fquickest6_2eh',['Convection_1D_ULTIMATE_QUICKEST6.h',['../_convection__1_d___u_l_t_i_m_a_t_e___q_u_i_c_k_e_s_t6_8h.html',1,'']]],
  ['convection_5f2d',['Convection_2D',['../_convection__2_d_8cpp.html#a79cbbb502158c5becac43d3b960cd91a',1,'Convection_2D(Matrix2D&lt; double &gt; &amp;PSD_PR, Matrix2D&lt; double &gt; P, Matrix2D&lt; double &gt; R, int P_size, int R_size, Matrix1D&lt; double &gt; P_LBC, Matrix1D&lt; double &gt; P_UBC, Matrix1D&lt; double &gt; R_LBC, Matrix1D&lt; double &gt; R_UBC, string P_LBC_type, string P_UBC_type, string R_LBC_type, string R_UBC_type, Matrix2D&lt; double &gt; VP, Matrix2D&lt; double &gt; VR, Matrix2D&lt; double &gt; Sources, Matrix2D&lt; double &gt; Losses, double dt_total, double min_PSD, double min_V):&#160;Convection_2D.cpp'],['../_convection__2_d_8h.html#a9c0f4ebd3cb7e921a243fc8ad34e28ce',1,'Convection_2D(Matrix2D&lt; double &gt; &amp;PSD_PR, Matrix2D&lt; double &gt; P, Matrix2D&lt; double &gt; R, int P_size, int R_size, Matrix1D&lt; double &gt; P_LBC, Matrix1D&lt; double &gt; P_UBC, Matrix1D&lt; double &gt; R_LBC, Matrix1D&lt; double &gt; R_UBC, string P_LBC_type, string P_UBC_type, string R_LBC_type, string R_UBC_type, Matrix2D&lt; double &gt; DP, Matrix2D&lt; double &gt; DR, Matrix2D&lt; double &gt; Sources, Matrix2D&lt; double &gt; Losses, double dt, double min_PSD, double min_V):&#160;Convection_2D.cpp']]],
  ['convection_5f2d_2ecpp',['Convection_2D.cpp',['../_convection__2_d_8cpp.html',1,'']]],
  ['convection_5f2d_2eh',['Convection_2D.h',['../_convection__2_d_8h.html',1,'']]],
  ['createinstance',['createInstance',['../class_logger.html#a954e6c1004836f9976c6b5baca2f1b20',1,'Logger']]],
  ['cubic1d',['Cubic1D',['../_interpolation_8cpp.html#a80d0e71a50aa60eb34af707a5415a37f',1,'Cubic1D(Matrix1D&lt; double &gt; &amp;old_grid, Matrix1D&lt; double &gt; &amp;values, Matrix1D&lt; double &gt; &amp;new_grid):&#160;Interpolation.cpp'],['../_interpolation_8h.html#a785af04709e2ccb19ae567d350baba4a',1,'Cubic1D(Matrix1D&lt; double &gt; &amp;old_grid, Matrix1D&lt; double &gt; &amp;f, Matrix1D&lt; double &gt; &amp;new_grid):&#160;Interpolation.cpp']]]
];
